import json
from pathlib import Path

from osip_dashboard.main import app


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "docs" / "openapi.json"
FRONTEND_CLIENT_PATH = ROOT / "frontend" / "src" / "api" / "client.ts"
FRONTEND_TYPES_PATH = ROOT / "frontend" / "src" / "api" / "types.ts"
GENERATED_SCHEMA_PATH = ROOT / "frontend" / "src" / "api" / "schema.d.ts"


def test_committed_openapi_contract_is_current_and_fully_typed():
    generated = app.openapi()
    committed = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    assert committed == generated, "Run .venv/bin/python scripts/export_openapi.py"

    operation_ids: set[str] = set()
    json_operations = 0
    for path, path_item in generated["paths"].items():
        for method, operation in path_item.items():
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            operation_id = operation["operationId"]
            assert operation_id not in operation_ids
            operation_ids.add(operation_id)
            if path.startswith("/health"):
                continue
            responses = operation["responses"]
            success_code = next((code for code in ("200", "201", "202", "204") if code in responses), None)
            assert success_code is not None, f"Missing successful response for {method.upper()} {path}"
            success = responses[success_code]
            schema = success["content"].get("application/json", {}).get("schema")
            if not schema:
                continue
            json_operations += 1
            assert schema, f"Missing response schema for {method.upper()} {path}"

    assert json_operations >= 22
    assert len(generated["components"]["schemas"]) >= 50


def test_frontend_uses_generated_paths_and_schemas_instead_of_handwritten_fetch_contracts():
    client = FRONTEND_CLIENT_PATH.read_text(encoding="utf-8")
    aliases = FRONTEND_TYPES_PATH.read_text(encoding="utf-8")
    generated = GENERATED_SCHEMA_PATH.read_text(encoding="utf-8")

    assert 'import type { paths } from "./schema"' in client
    assert "createClient<paths>" in client
    assert "fetch(" not in client
    assert 'import type { components } from "./schema"' in aliases
    assert "export interface" not in aliases
    assert "This file was auto-generated by openapi-typescript" in generated
